name: 'AppBuilder Install'
description: 'Install Appbuilder for Tests'
inputs:
  stack:  # id of input
    description: 'Docker stack reference'
    required: false
    default: 'ab'
  folder:  # id of input
    description: 'Folder to install in'
    required: false
    default: 'AppBuilder'
  port:  # id of input
    description: 'Port to use for the main stack'
    required: false
    default: '80'
  runtime:  # id of input
    description: 'Runtime to use for ab_runtime test'
    required: false
    default: null
        
# outputs:
#   time: # output will be available to future steps
#     description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/index.js'
